name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:    # Allows manual triggering

permissions:
  contents: write       # Required to push to repository
  pages: write          # Required for GitHub Pages
  id-token: write       # Required for OIDC

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: vimah
          svg_out_path: output/github-contribution-grid-snake.svg
          
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
